version: "3.7"
volumes:
  Shared:

services:
  website:
    deploy:
      replicas: 10
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: "50M"
          cpus: "0.1"
    image: "library/hello-world:latest"
    labels:
      Name: "Hello world"
      Env: "Dev"
      Created_by: "farrukh"
    ports:
      - "80:80/tcp"
    volumes:
      - "Shared:/Shared"



  db:
    image: "hello-world"
    labels:
      Name: "db"
      Env: "Dev"
      Created_by: "farrukh"
    ports:
      - "3306:3306/tcp"
    volumes:
      - "Shared:/Shared"
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: "50M"
          cpus: "0.1"

  lb:
    image: "nginx"
    labels:
      Name: "lb"
      Env: "Dev"
      Created_by: "farrukh"
    ports:
      - "8080:8080/tcp"
    volumes:
      - "Shared:/Shared"
    deploy:
      replicas: 5
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: "50M"
          cpus: "0.1"









root@docker
